# This workflow will install the environment, run the usecase param_wall

name: Tests for pgdrome

on: [push]

env:
  CACHE_NUMBER: 1 # increase to reset cache manually

jobs:
    usecase:
        runs-on: ubuntu-latest

        steps:
          - name: checkout repo content
            uses: actions/checkout@v2
          - name: Setup Mambaforge
            uses: conda-incubator/setup-miniconda@v2
            with:
                miniforge-variant: Mambaforge
                miniforge-version: latest
                activate-environment: amworkflow
                use-mamba: true

          - name: Set cache date
            run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

          - uses: actions/cache@v2
            with:
              path: "/usr/share/miniconda3/envs/amworkflow"
              key: conda-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
            id: cache

          - name: Update environment
            run: mamba env update -n amworkflow -f environment.yml
            if: steps.cache.outputs.cache-hit != 'true'

          - name: Install package
            run: git clone https://github.com/tpaviot/pythonocc-utils.git && cd pythonocc-utils && pip install -e .

          - name: Run param_wall
            shell: bash -l {0} #new shell
            run: |
              python usecases/param_wall/param_wall.py 
