# This workflow will install the environment, run the usecase param_wall

name: Test

on: [push]

jobs:
  # Run tests
  test_model:
    name: Run tests
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge
        channel-priority: strict
        auto-update-conda: true
        environment-file: environment.yaml

    - name: Install package
      run: git clone https://github.com/tpaviot/pythonocc-utils.git && pip install ./pythonocc-utils

    - name: Run param_wall
      shell: bash -l {0} #new shell
      run: |
        python usecases/param_wall/param_wall.py 
